name: avail_itech_hackfest
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"
dependencies:
  cached_network_image: ^3.2.1
  card_swiper: ^2.0.4
  cloud_firestore: ^3.4.5
  csc_picker: ^0.2.7
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.6.4
  firebase_core: ^1.21.0
  firebase_storage: ^10.3.6
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0
  fluttertoast: ^8.0.9
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  google_maps_flutter: ^2.2.5
  hexcolor: ^2.0.7
  hidden_drawer_menu: ^3.0.1
  image_cropper: ^1.4.1
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  permission_handler: ^10.2.0
  share_plus: ^6.3.1
  shared_preferences: ^2.0.20
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icon:
  android: true
  ios: true
  image_path: assets/logo/logo.png

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/images/

  fonts:
    - family: productSans
      fonts:
        - asset: assets/fonts/productSans.ttf
